services:
  auth.provider.reckless:
    class: s9e\reckless\AuthProvider
    parent: auth.provider.db
    arguments:
      - '@dbal.conn'
      - '@config'
      - '@passwords.manager'
      - '@request'
      - '@user'
      - '@service_container'
      - '%core.root_path%'
      - '%core.php_ext%'
    tags:
      - { name: auth.provider }

  profilefields.manager:
    class: s9e\reckless\Brofilefields
    arguments:
      - '@auth'
      - '@config_text'
      - '@dbal.conn'
      - '@dbal.tools'
      - '@dispatcher'
      - '@language'
      - '@log'
      - '@request'
      - '@template'
      - '@profilefields.type_collection'
      - '@user'
      - '%tables.profile_fields%'
      - '%tables.profile_fields_data%'
      - '%tables.profile_fields_options_language%'
      - '%tables.profile_fields_language%'
    calls:
      - [setCache, ['@cache.driver']]

  s9e.reckless.listener:
    class: s9e\reckless\Listener
    arguments:
      - '@config'
      - '@dbal.conn'
      - '%tables.topics%'
    tags:
      - { name: event.listener }

  template.twig.lexer:
    class: s9e\reckless\Flexer
    lazy: true
    arguments:
      - '@template.twig.environment'
