services:
  s9e.reckless.listener:
    class: s9e\reckless\listener
    arguments:
      - '@dbal.conn'
      - '%tables.topics%'
    tags:
      - { name: event.listener }

  template.twig.lexer:
      class: s9e\reckless\flexer
      lazy: true
      arguments:
        - '@template.twig.environment'
